### ISSUE TITLE
How do I set up an env file?

### ISSUE THREAD

**Issue by pisudayo** [chloefrfr/ChronosPublic#8]
How do I set up an env file?

**Comment by niou5** [comment]
did you manage it?

**Comment by pisudayo** [comment]
matchmaker doesn't work, but other than that, it's working.

**Comment by niou5** [comment]
i cant even get it to work i get this i get this error i set up everything correctly 41 | tcp: Bun.env.tcp === "true" || Bun.env.tcp === undefined ? true : false,
42 | });
43 |
44 | // Check if parsing was successful
45 | if (!parsedConfig.success)
46 | throw new Error(parsedConfig.error.errors.map((err) => err.message).join("\n"));
^
error: Expected number, received nan
Required
Required
Required
Required
Expected number, received nan
Required
Required
Required
Required
Required
at new Config (C:\Users\xristos\Desktop\ChronosPublic-main\src\wrappers\Env.wrapper.ts:46:13)
at C:\Users\xristos\Desktop\ChronosPublic-main\src\utilities\managers\QuestManager.ts:72:16

Bun v1.1.33 (Windows x64)
Press any key to continue . . .

**Comment by niou5** [comment]
can you tell me how you set it up cause i just cant it always shows that when i am not doing anything wrong
